# -*- coding: utf-8 -*-
"""
Bloco C — Documentos Fiscais relativos a Mercadorias (ICMS/IPI).
"""

REGISTROS_BLOCO_C = {
    "C001": {"REG": 0, "IND_MOV": 1},
    "C100": {
        "REG": 0, "IND_OPER": 1, "IND_EMIT": 2, "COD_PART": 3, "COD_MOD": 4,
        "COD_SIT": 5, "SER": 6, "NUM_DOC": 7, "CHV_NFE": 8, "DT_DOC": 9,
        "DT_E_S": 10, "VL_DOC": 11, "IND_PGTO": 12, "VL_DESC": 13,
        "VL_ABAT_NT": 14, "VL_MERC": 15, "IND_FRT": 16, "VL_FRT": 17,
        "VL_SEG": 18, "VL_OUT_DA": 19, "VL_BC_ICMS": 20, "VL_ICMS": 21,
        "VL_BC_ICMS_ST": 22, "VL_ICMS_ST": 23, "VL_IPI": 24,
        "VL_PIS": 25, "VL_COFINS": 26, "VL_PIS_ST": 27, "VL_COFINS_ST": 28,
    },
    "C101": {"REG": 0, "VL_FCP_UF_DEST": 1, "VL_ICMS_UF_DEST": 2, "VL_ICMS_UF_REM": 3},
    "C105": {"REG": 0, "OPER": 1, "UF": 2},
    "C110": {"REG": 0, "COD_INF": 1, "TXT_COMPL": 2},
    "C111": {"REG": 0, "NUM_PROC": 1, "IND_PROC": 2},
    "C112": {
        "REG": 0, "COD_DA": 1, "UF": 2, "NUM_DA": 3, "COD_AUT": 4,
        "VL_DA": 5, "DT_VCTO": 6, "DT_PGTO": 7,
    },
    "C113": {
        "REG": 0, "IND_OPER": 1, "IND_EMIT": 2, "COD_PART": 3,
        "COD_MOD": 4, "SER": 5, "SUB": 6, "NUM_DOC": 7, "DT_DOC": 8,
        "CHV_NFE": 9,
    },
    "C114": {
        "REG": 0, "COD_MOD": 1, "ECF_FAB": 2, "ECF_CX": 3,
        "NUM_DOC": 4, "DT_DOC": 5,
    },
    "C115": {
        "REG": 0, "IND_CARGA": 1, "CNPJ_COL": 2, "IE_COL": 3,
        "CPF_COL": 4, "COD_MUN_COL": 5, "CNPJ_ENTG": 6, "IE_ENTG": 7,
        "CPF_ENTG": 8, "COD_MUN_ENTG": 9,
    },
    "C116": {"REG": 0, "COD_MOD": 1, "NR_SAT": 2, "CHV_CFE": 3, "NUM_CFE": 4, "DT_DOC": 5},
    "C120": {"REG": 0, "COD_DOC_IMP": 1, "NUM_DOC_IMP": 2, "PIS_IMP": 3, "COFINS_IMP": 4, "NUM_ACDRAW": 5},
    "C170": {
        "REG": 0, "NUM_ITEM": 1, "COD_ITEM": 2, "DESCR_COMPL": 3,
        "QTD": 4, "UNID": 5, "VL_ITEM": 6, "VL_DESC": 7,
        "IND_MOV": 8, "CST_ICMS": 9, "CFOP": 10, "COD_NAT": 11,
        "VL_BC_ICMS": 12, "ALIQ_ICMS": 13, "VL_ICMS": 14,
        "VL_BC_ICMS_ST": 15, "ALIQ_ST": 16, "VL_ICMS_ST": 17,
        "IND_APUR": 18, "CST_IPI": 19, "COD_ENQ": 20,
        "VL_BC_IPI": 21, "ALIQ_IPI": 22, "VL_IPI": 23,
        "CST_PIS": 24, "VL_BC_PIS": 25, "ALIQ_PIS": 26, "QUANT_BC_PIS": 27,
        "ALIQ_PIS_QUANT": 28, "VL_PIS": 29,
        "CST_COFINS": 30, "VL_BC_COFINS": 31, "ALIQ_COFINS": 32,
        "QUANT_BC_COFINS": 33, "ALIQ_COFINS_QUANT": 34, "VL_COFINS": 35,
        "COD_CTA": 36, "VL_ABAT_NT": 37,
    },
    "C171": {"REG": 0, "NUM_TANQUE": 1, "QTDE": 2},
    "C172": {"REG": 0, "VL_BC_ISSQN": 1, "ALIQ_ISSQN": 2, "VL_ISSQN": 3},
    "C173": {
        "REG": 0, "LOTE_MED": 1, "QTD_ITEM": 2, "DT_FAB": 3,
        "DT_VAL": 4, "IND_MED": 5, "TP_PROD": 6, "VL_TAB_MAX": 7,
    },
    "C174": {"REG": 0, "IND_ARM": 1, "NUM_ARM": 2, "DESCR_COMPL": 3},
    "C175": {"REG": 0, "IND_VEIC_OPER": 1, "CNPJ": 2, "UF": 3, "CHASSI_VEIC": 4},
    "C176": {
        "REG": 0, "COD_MOD_ULT_E": 1, "NUM_DOC_ULT_E": 2, "SER_ULT_E": 3,
        "DT_ULT_E": 4, "COD_PART_ULT_E": 5, "QUANT_ULT_E": 6,
        "VL_UNIT_ULT_E": 7, "VL_UNIT_BC_ST": 8,
    },
    "C177": {"REG": 0, "COD_SELO_IPI": 1, "QT_SELO_IPI": 2},
    "C178": {"REG": 0, "CL_ENQ": 1, "VL_UNID": 2, "QUANT_PAD": 3},
    "C179": {"REG": 0, "BC_ST_ORIG_DEST": 1, "ICMS_ST_REP": 2, "ICMS_ST_COMPL": 3, "BC_RET": 4, "ICMS_RET": 5},
    "C190": {
        "REG": 0, "CST_ICMS": 1, "CFOP": 2, "ALIQ_ICMS": 3,
        "VL_OPR": 4, "VL_BC_ICMS": 5, "VL_ICMS": 6,
        "VL_BC_ICMS_ST": 7, "VL_ICMS_ST": 8, "VL_RED_BC": 9,
        "VL_IPI": 10, "COD_OBS": 11,
    },
    "C191": {"REG": 0, "VL_FCP_OP": 1, "VL_FCP_ST": 2, "VL_FCP_RET": 3},
    "C195": {"REG": 0, "COD_OBS": 1, "TXT_COMPL": 2},
    "C197": {
        "REG": 0, "COD_AJ": 1, "DESCR_COMPL_AJ": 2, "COD_ITEM": 3,
        "VL_BC_ICMS": 4, "ALIQ_ICMS": 5, "VL_ICMS": 6,
        "VL_OUTROS": 7,
    },
    "C300": {
        "REG": 0, "COD_MOD": 1, "SER": 2, "SUB": 3, "NUM_DOC_INI": 4,
        "NUM_DOC_FIN": 5, "DT_DOC": 6, "VL_DOC": 7, "VL_PIS": 8,
        "VL_COFINS": 9, "COD_CTA": 10,
    },
    "C310": {"REG": 0, "NUM_DOC_CANC": 1},
    "C320": {
        "REG": 0, "CST_ICMS": 1, "CFOP": 2, "ALIQ_ICMS": 3,
        "VL_OPR": 4, "VL_BC_ICMS": 5, "VL_ICMS": 6,
        "VL_RED_BC": 7, "COD_OBS": 8,
    },
    "C321": {"REG": 0, "COD_ITEM": 1, "QTD": 2, "UNID": 3, "VL_ITEM": 4, "VL_DESC": 5, "VL_BC_ICMS": 6, "VL_ICMS": 7, "VL_PIS": 8, "VL_COFINS": 9},
    "C350": {"REG": 0, "SER": 1, "SUB_SER": 2, "NUM_DOC": 3, "DT_DOC": 4, "CNPJ_CPF": 5, "VL_MERC": 6, "VL_DOC": 7, "VL_DESC": 8, "VL_PIS": 9, "VL_COFINS": 10, "COD_CTA": 11},
    "C370": {"REG": 0, "NUM_ITEM": 1, "COD_ITEM": 2, "QTD": 3, "UNID": 4, "VL_ITEM": 5, "VL_DESC": 6},
    "C390": {"REG": 0, "CST_ICMS": 1, "CFOP": 2, "ALIQ_ICMS": 3, "VL_OPR": 4, "VL_BC_ICMS": 5, "VL_ICMS": 6, "VL_RED_BC": 7, "COD_OBS": 8},
    "C400": {"REG": 0, "COD_MOD": 1, "ECF_MOD": 2, "ECF_FAB": 3, "ECF_CX": 4},
    "C405": {"REG": 0, "DT_DOC": 1, "CRO": 2, "CRZ": 3, "NUM_COO_FIN": 4, "GT_FIN": 5, "VL_BRT": 6},
    "C410": {"REG": 0, "VL_PIS": 1, "VL_COFINS": 2},
    "C420": {"REG": 0, "COD_TOT_PAR": 1, "VLR_ACUM_TOT": 2, "NR_TOT": 3, "DESCR_NR_TOT": 4},
    "C425": {"REG": 0, "COD_ITEM": 1, "QTD": 2, "UNID": 3, "VL_ITEM": 4, "VL_PIS": 5, "VL_COFINS": 6},
    "C460": {"REG": 0, "COD_MOD": 1, "COD_SIT": 2, "NUM_DOC": 3, "DT_DOC": 4, "VL_DOC": 5, "VL_PIS": 6, "VL_COFINS": 7, "CPF_CNPJ": 8, "NOM_ADQ": 9},
    "C470": {"REG": 0, "COD_ITEM": 1, "QTD": 2, "QTD_CANC": 3, "UNID": 4, "VL_ITEM": 5, "CST_ICMS": 6, "CFOP": 7, "ALIQ_ICMS": 8, "VL_PIS": 9, "VL_COFINS": 10},
    "C490": {"REG": 0, "CST_ICMS": 1, "CFOP": 2, "ALIQ_ICMS": 3, "VL_OPR": 4, "VL_BC_ICMS": 5, "VL_ICMS": 6, "COD_OBS": 7},
    "C495": {"REG": 0, "ALIQ_ICMS": 1, "COD_ITEM": 2, "QTD": 3, "QTD_CANC": 4, "UNID": 5, "VL_ITEM": 6, "VL_DESC": 7, "VL_CANC": 8, "VL_ACMO": 9, "VL_BC_ICMS": 10, "VL_ICMS": 11, "VL_ISEN": 12, "VL_NT": 13, "VL_ICMS_ST": 14},
    "C500": {
        "REG": 0, "IND_OPER": 1, "IND_EMIT": 2, "COD_PART": 3,
        "COD_MOD": 4, "COD_SIT": 5, "SER": 6, "SUB": 7, "COD_CONS": 8,
        "NUM_DOC": 9, "DT_DOC": 10, "DT_E_S": 11, "VL_DOC": 12,
        "VL_DESC": 13, "VL_FORN": 14, "VL_SERV_NT": 15, "VL_TERC": 16,
        "VL_DA": 17, "VL_BC_ICMS": 18, "VL_ICMS": 19, "VL_BC_ICMS_ST": 20,
        "VL_ICMS_ST": 21, "COD_INF": 22, "VL_PIS": 23, "VL_COFINS": 24,
        "TP_LIGACAO": 25, "COD_GRUPO_TENSAO": 26,
    },
    "C510": {"REG": 0, "NUM_ITEM": 1, "COD_ITEM": 2, "COD_CLASS": 3, "QTD": 4, "UNID": 5, "VL_ITEM": 6, "VL_DESC": 7, "CST_ICMS": 8, "CFOP": 9, "VL_BC_ICMS": 10, "ALIQ_ICMS": 11, "VL_ICMS": 12, "VL_BC_ICMS_ST": 13, "ALIQ_ST": 14, "VL_ICMS_ST": 15, "IND_REC": 16, "COD_PART": 17, "VL_PIS": 18, "VL_COFINS": 19, "COD_CTA": 20},
    "C590": {"REG": 0, "CST_ICMS": 1, "CFOP": 2, "ALIQ_ICMS": 3, "VL_OPR": 4, "VL_BC_ICMS": 5, "VL_ICMS": 6, "VL_BC_ICMS_ST": 7, "VL_ICMS_ST": 8, "VL_RED_BC": 9, "COD_OBS": 10},
    "C591": {"REG": 0, "VL_FCP_OP": 1, "VL_FCP_ST": 2},
    "C595": {"REG": 0, "COD_OBS": 1, "TXT_COMPL": 2},
    "C597": {"REG": 0, "COD_AJ": 1, "DESCR_COMPL_AJ": 2, "COD_ITEM": 3, "VL_BC_ICMS": 4, "ALIQ_ICMS": 5, "VL_ICMS": 6, "VL_OUTROS": 7},
    "C600": {"REG": 0, "COD_MOD": 1, "COD_MUN": 2, "SER": 3, "SUB": 4, "COD_CONS": 5, "QTD_CONS": 6, "QTD_CANC": 7, "DT_DOC": 8, "VL_DOC": 9, "VL_DESC": 10, "CONS": 11, "VL_FORN": 12, "VL_SERV_NT": 13, "VL_TERC": 14, "VL_DA": 15, "VL_BC_ICMS": 16, "VL_ICMS": 17, "VL_BC_ICMS_ST": 18, "VL_ICMS_ST": 19, "VL_PIS": 20, "VL_COFINS": 21},
    "C601": {"REG": 0, "VL_FCP_OP": 1, "VL_FCP_ST": 2},
    "C610": {"REG": 0, "COD_CLASS": 1, "COD_ITEM": 2, "QTD": 3, "UNID": 4, "VL_ITEM": 5, "VL_DESC": 6, "CST_ICMS": 7, "CFOP": 8, "ALIQ_ICMS": 9, "VL_BC_ICMS": 10, "VL_ICMS": 11, "VL_BC_ICMS_ST": 12, "ALIQ_ST": 13, "VL_ICMS_ST": 14, "VL_PIS": 15, "VL_COFINS": 16, "COD_CTA": 17},
    "C690": {"REG": 0, "CST_ICMS": 1, "CFOP": 2, "ALIQ_ICMS": 3, "VL_OPR": 4, "VL_BC_ICMS": 5, "VL_ICMS": 6, "VL_BC_ICMS_ST": 7, "VL_ICMS_ST": 8, "VL_RED_BC": 9, "COD_OBS": 10},
    "C700": {"REG": 0, "COD_MOD": 1, "SER": 2, "NRO_ORD_INI": 3, "NRO_ORD_FIN": 4, "DT_DOC_INI": 5, "DT_DOC_FIN": 6, "NOM_MEST": 7, "CHV_COD_DIG": 8},
    "C790": {"REG": 0, "CST_ICMS": 1, "CFOP": 2, "ALIQ_ICMS": 3, "VL_OPR": 4, "VL_BC_ICMS": 5, "VL_ICMS": 6, "VL_BC_ICMS_ST": 7, "VL_ICMS_ST": 8, "VL_RED_BC": 9, "COD_OBS": 10},
    "C791": {"REG": 0, "UF": 1, "VL_BC_ICMS_ST": 2, "VL_ICMS_ST": 3},
    "C800": {"REG": 0, "COD_MOD": 1, "COD_SIT": 2, "NUM_CFE": 3, "DT_DOC": 4, "VL_CFE": 5, "VL_PIS": 6, "VL_COFINS": 7, "CNPJ_CPF": 8, "NR_SAT": 9, "CHV_CFE": 10, "VL_DESC": 11, "VL_MERC": 12, "VL_OUT_DA": 13, "VL_ICMS": 14, "VL_PIS_ST": 15, "VL_COFINS_ST": 16},
    "C810": {"REG": 0, "NUM_ITEM": 1, "COD_ITEM": 2, "QTD": 3, "UNID": 4, "VL_ITEM": 5, "CST_ICMS": 6, "CFOP": 7},
    "C815": {"REG": 0, "COD_MOT_REST_COMPL": 1, "QUANT_CONV": 2, "UNID": 3, "VL_UNIT_CONV": 4, "VL_UNIT_ICMS_NA_OPERACAO_CONV": 5, "VL_UNIT_ICMS_OP_CONV": 6, "VL_UNIT_ICMS_OP_ESTOQUE_CONV": 7, "VL_UNIT_ICMS_ST_ESTOQUE_CONV": 8, "VL_UNIT_FCP_ICMS_ST_ESTOQUE_CONV": 9, "VL_UNIT_ICMS_ST_CONV_REST": 10, "VL_UNIT_FCP_ST_CONV_REST": 11, "VL_UNIT_ICMS_ST_CONV_COMPL": 12, "VL_UNIT_FCP_ST_CONV_COMPL": 13},
    "C850": {"REG": 0, "CST_ICMS": 1, "CFOP": 2, "ALIQ_ICMS": 3, "VL_OPR": 4, "VL_BC_ICMS": 5, "VL_ICMS": 6, "COD_OBS": 7},
    "C855": {"REG": 0, "COD_MOT_REST_COMPL": 1, "QUANT_CONV": 2, "UNID": 3, "VL_UNIT_CONV": 4, "VL_UNIT_ICMS_NA_OPERACAO_CONV": 5, "VL_UNIT_ICMS_OP_CONV": 6, "VL_UNIT_ICMS_OP_ESTOQUE_CONV": 7, "VL_UNIT_ICMS_ST_ESTOQUE_CONV": 8, "VL_UNIT_FCP_ICMS_ST_ESTOQUE_CONV": 9, "VL_UNIT_ICMS_ST_CONV_REST": 10, "VL_UNIT_FCP_ST_CONV_REST": 11, "VL_UNIT_ICMS_ST_CONV_COMPL": 12, "VL_UNIT_FCP_ST_CONV_COMPL": 13},
    "C860": {"REG": 0, "COD_MOD": 1, "NR_SAT": 2, "DT_DOC": 3, "DOC_INI": 4, "DOC_FIN": 5},
    "C870": {"REG": 0, "COD_ITEM": 1, "QTD": 2, "UNID": 3, "CST_ICMS": 4, "CFOP": 5},
    "C880": {"REG": 0, "COD_MOT_REST_COMPL": 1, "QUANT_CONV": 2, "UNID": 3, "VL_UNIT_CONV": 4, "VL_UNIT_ICMS_NA_OPERACAO_CONV": 5, "VL_UNIT_ICMS_OP_CONV": 6, "VL_UNIT_ICMS_OP_ESTOQUE_CONV": 7, "VL_UNIT_ICMS_ST_ESTOQUE_CONV": 8, "VL_UNIT_FCP_ICMS_ST_ESTOQUE_CONV": 9, "VL_UNIT_ICMS_ST_CONV_REST": 10, "VL_UNIT_FCP_ST_CONV_REST": 11, "VL_UNIT_ICMS_ST_CONV_COMPL": 12, "VL_UNIT_FCP_ST_CONV_COMPL": 13},
    "C890": {"REG": 0, "CST_ICMS": 1, "CFOP": 2, "ALIQ_ICMS": 3, "VL_OPR": 4, "VL_BC_ICMS": 5, "VL_ICMS": 6, "COD_OBS": 7},
    "C895": {"REG": 0, "COD_MOT_REST_COMPL": 1, "QUANT_CONV": 2, "UNID": 3, "VL_UNIT_CONV": 4, "VL_UNIT_ICMS_NA_OPERACAO_CONV": 5, "VL_UNIT_ICMS_OP_CONV": 6, "VL_UNIT_ICMS_OP_ESTOQUE_CONV": 7, "VL_UNIT_ICMS_ST_ESTOQUE_CONV": 8, "VL_UNIT_FCP_ICMS_ST_ESTOQUE_CONV": 9, "VL_UNIT_ICMS_ST_CONV_REST": 10, "VL_UNIT_FCP_ST_CONV_REST": 11, "VL_UNIT_ICMS_ST_CONV_COMPL": 12, "VL_UNIT_FCP_ST_CONV_COMPL": 13},
    "C990": {"REG": 0, "QTD_LIN_C": 1},
}
