# -*- coding: utf-8 -*-
"""
Bloco D — Documentos Fiscais relativos a Serviços (ICMS).
CT-e, Bilhetes de passagem, etc.
"""

REGISTROS_BLOCO_D = {
    "D001": {"REG": 0, "IND_MOV": 1},
    "D100": {
        "REG": 0, "IND_OPER": 1, "IND_EMIT": 2, "COD_PART": 3,
        "COD_MOD": 4, "COD_SIT": 5, "SER": 6, "SUB": 7, "NUM_DOC": 8,
        "CHV_CTE": 9, "DT_DOC": 10, "DT_A_P": 11, "TP_CT_E": 12,
        "CHV_CTE_REF": 13, "VL_DOC": 14, "VL_DESC": 15, "IND_FRT": 16,
        "VL_SERV": 17, "VL_BC_ICMS": 18, "VL_ICMS": 19, "VL_NT": 20,
        "COD_INF": 21, "COD_CTA": 22, "COD_MUN_ORIG": 23, "COD_MUN_DEST": 24,
    },
    "D101": {"REG": 0, "VL_FCP_UF_DEST": 1, "VL_ICMS_UF_DEST": 2, "VL_ICMS_UF_REM": 3},
    "D110": {"REG": 0, "NUM_ITEM": 1, "COD_ITEM": 2, "VL_SERV": 3, "VL_OUT": 4},
    "D120": {"REG": 0, "COD_MUN_ORIG": 1, "COD_MUN_DEST": 2, "VEIC_ID": 3, "UF_ID": 4},
    "D130": {
        "REG": 0, "COD_PART_CONSG": 1, "COD_PART_RED": 2,
        "IND_FRT_RED": 3, "COD_MUN_ORIG": 4, "COD_MUN_DEST": 5,
        "VEIC_ID": 6, "VL_LIQ_FRT": 7, "VL_SEC_CAT": 8,
        "VL_DESP": 9, "VL_PEDG": 10, "VL_OUT": 11, "VL_FRT": 12,
        "UF_ID": 13,
    },
    "D140": {"REG": 0, "COD_PART_CONSG": 1, "COD_MUN_ORIG": 2, "COD_MUN_DEST": 3, "IND_VEIC": 4, "VEIC_ID": 5, "IND_NAV": 6, "VIAGEM": 7, "VL_FRT_LIQ": 8, "VL_DESP_PORT": 9, "VL_DESP_CAR_DESC": 10, "VL_OUT": 11, "VL_FRT_BRT": 12, "VL_FRT_MM": 13},
    "D150": {"REG": 0, "COD_MUN_ORIG": 1, "COD_MUN_DEST": 2, "VEIC_ID": 3, "VIAGEM": 4, "IND_TFA": 5, "VL_PESO_TX": 6, "VL_TX_TERR": 7, "VL_TX_RED": 8, "VL_OUT": 9, "VL_TX_ADV": 10},
    "D160": {"REG": 0, "DESPACHO": 1, "CNPJ_CPF_REM": 2, "IE_REM": 3, "COD_MUN_ORI": 4, "CNPJ_CPF_DEST": 5, "IE_DEST": 6, "COD_MUN_DEST": 7},
    "D161": {"REG": 0, "IND_CARGA": 1, "CNPJ_CPF_COL": 2, "IE_COL": 3, "COD_MUN_COL": 4, "CNPJ_CPF_ENTG": 5, "IE_ENTG": 6, "COD_MUN_ENTG": 7},
    "D162": {"REG": 0, "COD_MOD": 1, "SER": 2, "NUM_DOC": 3, "DT_DOC": 4, "VL_DOC": 5, "VL_MERC": 6, "QTD_VOL": 7, "PESO_BRT": 8, "PESO_LIQ": 9},
    "D170": {"REG": 0, "COD_PART_CONSG": 1, "COD_PART_RED": 2, "COD_MUN_ORIG": 3, "COD_MUN_DEST": 4, "OTM": 5, "IND_NAT_FRT": 6, "VL_LIQ_FRT": 7, "VL_GRIS": 8, "VL_PDG": 9, "VL_OUT": 10, "VL_FRT": 11, "VEIC_ID": 12, "UF_ID": 13},
    "D180": {"REG": 0, "NUM_SEQ": 1, "IND_EMIT": 2, "CNPJ_CPF_EMIT": 3, "UF_EMIT": 4, "IE_EMIT": 5, "COD_MUN_ORIG": 6, "CNPJ_CPF_TOM": 7, "UF_TOM": 8, "IE_TOM": 9, "COD_MUN_DEST": 10, "COD_MOD": 11, "SER": 12, "SUB": 13, "NUM_DOC": 14, "DT_DOC": 15, "VL_DOC": 16},
    "D190": {
        "REG": 0, "CST_ICMS": 1, "CFOP": 2, "ALIQ_ICMS": 3,
        "VL_OPR": 4, "VL_BC_ICMS": 5, "VL_ICMS": 6,
        "VL_RED_BC": 7, "COD_OBS": 8,
    },
    "D195": {"REG": 0, "COD_OBS": 1, "TXT_COMPL": 2},
    "D197": {
        "REG": 0, "COD_AJ": 1, "DESCR_COMPL_AJ": 2, "COD_ITEM": 3,
        "VL_BC_ICMS": 4, "ALIQ_ICMS": 5, "VL_ICMS": 6, "VL_OUTROS": 7,
    },
    "D300": {"REG": 0, "COD_MOD": 1, "SER": 2, "SUB": 3, "NUM_DOC_INI": 4, "NUM_DOC_FIN": 5, "CST_ICMS": 6, "CFOP": 7, "ALIQ_ICMS": 8, "DT_DOC": 9, "VL_OPR": 10, "VL_DESC": 11, "VL_SERV": 12, "VL_SEG": 13, "VL_OUT_DESP": 14, "VL_BC_ICMS": 15, "VL_ICMS": 16, "VL_RED_BC": 17, "COD_OBS": 18},
    "D301": {"REG": 0, "NUM_DOC_CANC": 1},
    "D310": {"REG": 0, "COD_MUN_ORIG": 1, "VL_SERV": 2, "VL_BC_ICMS": 3, "VL_ICMS": 4},
    "D350": {"REG": 0, "COD_MOD": 1, "ECF_MOD": 2, "ECF_FAB": 3, "ECF_CX": 4},
    "D355": {"REG": 0, "DT_DOC": 1, "CRO": 2, "CRZ": 3, "NUM_COO_FIN": 4, "GT_FIN": 5, "VL_BRT": 6},
    "D360": {"REG": 0, "VL_PIS": 1, "VL_COFINS": 2},
    "D365": {"REG": 0, "COD_TOT_PAR": 1, "VLR_ACUM_TOT": 2, "NR_TOT": 3, "DESCR_NR_TOT": 4},
    "D370": {"REG": 0, "COD_MUN_ORIG": 1, "VL_SERV": 2, "QTD_BILH": 3, "VL_BC_ICMS": 4, "VL_ICMS": 5},
    "D390": {"REG": 0, "CST_ICMS": 1, "CFOP": 2, "ALIQ_ICMS": 3, "VL_OPR": 4, "VL_BC_ICMS": 5, "VL_ICMS": 6, "VL_RED_BC": 7, "COD_OBS": 8},
    "D400": {"REG": 0, "COD_PART": 1, "COD_MOD": 2, "COD_SIT": 3, "SER": 4, "SUB": 5, "NUM_DOC": 6, "DT_DOC": 7, "VL_DOC": 8, "VL_DESC": 9, "VL_SERV": 10, "VL_BC_ICMS": 11, "VL_ICMS": 12, "VL_PIS": 13, "VL_COFINS": 14, "COD_CTA": 15},
    "D410": {"REG": 0, "COD_MOD": 1, "SER": 2, "SUB": 3, "NUM_DOC_INI": 4, "NUM_DOC_FIN": 5, "DT_DOC": 6, "CST_ICMS": 7, "CFOP": 8, "ALIQ_ICMS": 9, "VL_OPR": 10, "VL_DESC": 11, "VL_SERV": 12, "VL_BC_ICMS": 13, "VL_ICMS": 14},
    "D411": {"REG": 0, "NUM_DOC_CANC": 1},
    "D420": {"REG": 0, "COD_MUN_ORIG": 1, "VL_SERV": 2, "VL_BC_ICMS": 3, "VL_ICMS": 4},
    "D500": {
        "REG": 0, "IND_OPER": 1, "IND_EMIT": 2, "COD_PART": 3,
        "COD_MOD": 4, "COD_SIT": 5, "SER": 6, "SUB": 7, "NUM_DOC": 8,
        "DT_DOC": 9, "DT_A_P": 10, "VL_DOC": 11, "VL_DESC": 12,
        "VL_SERV": 13, "VL_SERV_NT": 14, "VL_TERC": 15,
        "VL_DA": 16, "VL_BC_ICMS": 17, "VL_ICMS": 18,
        "COD_INF": 19, "VL_PIS": 20, "VL_COFINS": 21,
    },
    "D510": {"REG": 0, "NUM_ITEM": 1, "COD_ITEM": 2, "COD_CLASS": 3, "QTD": 4, "UNID": 5, "VL_ITEM": 6, "VL_DESC": 7, "CST_ICMS": 8, "CFOP": 9, "VL_BC_ICMS": 10, "ALIQ_ICMS": 11, "VL_ICMS": 12, "VL_BC_ICMS_ST": 13, "ALIQ_ST": 14, "VL_ICMS_ST": 15, "IND_REC": 16, "COD_PART": 17, "VL_PIS": 18, "VL_COFINS": 19, "COD_CTA": 20},
    "D530": {"REG": 0, "IND_SERV": 1, "DT_INI_SERV": 2, "DT_FIN_SERV": 3, "PER_FISCAL": 4, "COD_AREA": 5, "TERMINAL": 6},
    "D590": {"REG": 0, "CST_ICMS": 1, "CFOP": 2, "ALIQ_ICMS": 3, "VL_OPR": 4, "VL_BC_ICMS": 5, "VL_ICMS": 6, "VL_BC_ICMS_ST": 7, "VL_ICMS_ST": 8, "VL_RED_BC": 9, "COD_OBS": 10},
    "D600": {"REG": 0, "COD_MOD": 1, "COD_MUN": 2, "SER": 3, "SUB": 4, "COD_CONS": 5, "QTD_CONS": 6, "QTD_CANC": 7, "DT_DOC": 8, "VL_DOC": 9, "VL_DESC": 10, "VL_SERV": 11, "VL_SERV_NT": 12, "VL_TERC": 13, "VL_DA": 14, "VL_BC_ICMS": 15, "VL_ICMS": 16, "VL_PIS": 17, "VL_COFINS": 18},
    "D610": {"REG": 0, "COD_CLASS": 1, "COD_ITEM": 2, "QTD": 3, "UNID": 4, "VL_ITEM": 5, "VL_DESC": 6, "CST_ICMS": 7, "CFOP": 8, "ALIQ_ICMS": 9, "VL_BC_ICMS": 10, "VL_ICMS": 11, "VL_BC_ICMS_ST": 12, "ALIQ_ST": 13, "VL_ICMS_ST": 14, "VL_RED_BC": 15, "VL_PIS": 16, "VL_COFINS": 17, "COD_CTA": 18},
    "D690": {"REG": 0, "CST_ICMS": 1, "CFOP": 2, "ALIQ_ICMS": 3, "VL_OPR": 4, "VL_BC_ICMS": 5, "VL_ICMS": 6, "VL_BC_ICMS_ST": 7, "VL_ICMS_ST": 8, "VL_RED_BC": 9, "COD_OBS": 10},
    "D695": {"REG": 0, "COD_MOD": 1, "SER": 2, "NRO_ORD_INI": 3, "NRO_ORD_FIN": 4, "DT_DOC_INI": 5, "DT_DOC_FIN": 6, "NOM_MEST": 7, "CHV_COD_DIG": 8},
    "D696": {"REG": 0, "CST_ICMS": 1, "CFOP": 2, "ALIQ_ICMS": 3, "VL_OPR": 4, "VL_BC_ICMS": 5, "VL_ICMS": 6, "VL_BC_ICMS_ST": 7, "VL_ICMS_ST": 8, "VL_RED_BC": 9, "COD_OBS": 10},
    "D697": {"REG": 0, "UF": 1, "VL_BC_ICMS": 2, "VL_ICMS": 3},
    "D990": {"REG": 0, "QTD_LIN_D": 1},
}
